### ISSUE TITLE
直接就能跑起来吗

### ISSUE THREAD

**Issue by jiafuzhang** [PinTeh/Ant-Live#2]
是不是少了数据库的sql脚本

**Comment by PinTeh** [comment]
> 是不是少了数据库的sql脚本

少了sql脚本

**Comment by ansonham** [comment]
方便分享下 sql 脚本吗？

**Comment by PinTeh** [comment]
好的，改天有空我整理一下发出来



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月10日(星期天) 上午8:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PinTeh/Ant-Live] 直接就能跑起来吗 (#2)





 
方便分享下 sql 脚本吗？
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
